name: Build

on: push

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: abelfodil/protoc-action@v1
        with:
          protoc-version: "21.6"
      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1
      - run: go mod download
      - run: make
      - run: git status
      - run: git diff
      - run: git diff --quiet **.proto **.go
